version: "3.8"
services:
  portfolio_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_container
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    env_file:
      - .env.dev